### ISSUE TITLE
Global function usage only in error with phpstan but not in production/unit test despite migration doc

### ISSUE THREAD

**Issue by liqueurdetoile** [cakephp/app#979]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Application Skeleton Version: 5.0.1
* Platform and Target: PHP 8.2.11

Hey there,

Just starting with a fresh 5x app install, I was facing a phpstan error with the global translation function `__` : 

```
--------------------------------------------------------------------- 
  Line   Model\Table\WebsitesTable.php
 ------ ---------------------------------------------------------------------
  :96    Function __ not found.
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
 ------ ---------------------------------------------------------------------
```
Curiously my unit tests were working fine and not complaining about global `__` use. Wandering why, I've found out that my default app's `config/bootstrap.php` still has `require CAKE . 'functions.php';`.

I've read once (and forgot till now) in the migration guide that 

> Global functions are now opt-in. If your application uses global function aliases be sure to add require CAKE . 'functions.php' to you application’s config/bootstrap.php.

We're in the middle of the river with current setup 😬 Either, the default bootstrap should be updated (and my unit tests would have quick failed), either, default phpstan config should be updated :

```yaml
parameters:
    level: 8
    treatPhpDocTypesAsCertain: false
    checkGenericClassInNonGenericObjectType: false
    # add this one
    bootstrapFiles:
        - vendor/cakephp/cakephp/src/functions.php
    paths:
        - src/
```

Finally, it's also possible to get rid of these globals as they are now defined in namespace. For migration ease, they can be split in an optional compatibility plugin so [it won't lure IDE with *unrequired* globals if typing `__(` too  quickly](https://i.postimg.cc/59Rs723v/capture.png) if plugin is not installed.

It's a really quick and naive approach and I'm certainly missing many elements to say what is the best option. If using an IDE, last one seems to be the best though.

By the way, you've made a hard work with CakePHP 5.x. Thanks !
